---
- hosts: web01
  become: yes
  gather_facts: false
  tasks:
    - name: install apache2 on web01
      apt:
        name: apache2
        state: installed
    - name: start apache2 service
      service:
        name: apache2
        state: started
                          
